variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=/cache/.m2/repository -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dstyle.color=always"
  TELETASK_TEST_TEMPDIR: "/cache/jeletask"
  DOCKERHUB_IMAGE: "ridiekel/jeletask2mqtt"
  TERM: xterm-256color
  GRAALVM_VERSION: "25-graalce"
  MAVEN_VERSION: "3.9.12"

stages:
  - test
  - visualize
  - release

cache:
  paths:
    - ./.m2/repository

test-job:
  stage: test 
  image: ridiekel/base-test:latest
  tags:
    - amd64
  script:
    - |
      echo "Running native amd64 tests..."
      ./mvnw $MAVEN_CLI_OPTS -PnativeTest org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report
      cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit: 
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
    paths:
      - ./target/classes/*
      - ./target/site/jacoco/*
  rules:
    - if: $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: always

test-job-arm64:
  stage: test
  tags:
    - arm64
  script:
    - |
      MAVEN_OPTS=""
      echo "Installing graalvm if not yet present"
      sdk install java ${GRAALVM_VERSION}
      sdk use java ${GRAALVM_VERSION}
      echo "Installing maven if not yet present"
      sdk install maven ${MAVEN_VERSION}
      sdk use maven ${MAVEN_VERSION}
      echo "Running native arm64 tests..."
      ./mvnw $MAVEN_CLI_OPTS -PnativeTest verify
  rules:
    - if: $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: always

sonarqube-analysis:
  image: ridiekel/base-test:latest
  stage: visualize
  tags:
    - amd64
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  needs: ["test-job"]
  script: 
    - mvn $MAVEN_CLI_OPTS sonar:sonar -Dmaven.test.failure.ignore=true
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: always

code-coverage-report-conversion:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.11
  tags:
    - amd64
  script:
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  needs: ["test-job"]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/site/cobertura.xml
  rules:
    - if: $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: always

create-release:
  stage: release
  image: ridiekel/base-test:latest
  before_script:
    - |
      echo "Configuring..."
      echo "Email: $GITLAB_CI_EMAIL"
      echo "URL: $GITLAB_CI_URL"
      git config --global user.email "$GITLAB_CI_EMAIL"
      git config --global user.name "GitLab CI"
      git config --global url."$GITLAB_CI_URL".insteadOf "git@github.com:ridiekel/"
      which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
      eval $(ssh-agent -s)
      ssh-add <(echo "$GITLAB_CI_SSH_PRIVATE_KEY")
      mkdir -p ~/.ssh
      [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      git checkout -B "$CI_COMMIT_REF_NAME"
      echo $CI_JOB_ID
      echo GE_JOB_ID=$CI_JOB_ID >> variables.env
  script:
    - |
      ./mvnw -Darguments="-Dmaven.javadoc.skip=true -DskipTests=true" release:clean release:prepare -B
      cat release.properties | sed 's/^scm\./scm_/g' | grep scm_ >> variables.env
      cat variables.env
      ./mvnw -Darguments="-Dmaven.javadoc.skip=true -DskipTests=true" release:perform -B
  artifacts:
    paths:
      - target/jeletask*.jar
      - release.properties       # optioneel, handig voor debug
      - variables.env
      - Dockerfile
    reports:
      dotenv: variables.env
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\]prepare release.*/
      when: manual
      allow_failure: true

create-gitlab-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - amd64
  script:
    - |
      echo 'running release_job'
      echo 'Previous Job ID is printed below'
      echo ${GE_JOB_ID}
      echo ${scm_tag}
  needs:
    - job: create-release
      artifacts: true
  release:
    name: 'Release ${scm_tag}'
    description: 'Created using the release-cli'
    tag_name: '${scm_tag}'
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: on_success
      allow_failure: false

release-upload:
  stage: release
  image: alpine:latest
  tags:
    - amd64
  needs:
    - job: create-release
      artifacts: true
  before_script:
    - apk add --no-cache curl jq
  script:
    - |
      set -euo pipefail
      echo "scm_tag=${scm_tag:-}"
      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
      if [ -z "$TAG" ]; then
      echo "Tag niet gevonden (scm_tag of CI_COMMIT_TAG)";
      echo "Beschikbare bestanden:"; ls -la;
      exit 1;
      fi
      echo $TAG
      VERSION="${TAG#${CI_PROJECT_NAME}-}"
      echo "$VERSION"
      JAR="target/${CI_PROJECT_NAME}-${VERSION}.jar"
      [ -f "$JAR" ] || JAR="$(ls -1 target/*.jar | head -n1)"
      test -f "$JAR" || { echo "Geen JAR gevonden in target/"; exit 1; }
      ls -al $JAR
      UPLOAD_JSON="$(curl -sS -f -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" -F "file=@${JAR}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/uploads")"
      echo $UPLOAD_JSON
      FILE_URL="${CI_SERVER_URL}$(echo "$UPLOAD_JSON" | jq -r .full_path)"
      echo $FILE_URL
      ENC_TAG="$(printf %s "$TAG" | jq -sRr @uri)"
      echo $ENC_TAG
      curl -sS --fail-with-body -X POST -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
        --data-urlencode "name=$(basename "$JAR")" \
        --data-urlencode "url=${FILE_URL}" \
        --data-urlencode "link_type=package" \
        --data-urlencode "filepath=/$(basename "$JAR")" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/${ENC_TAG}/assets/links"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: on_success
      allow_failure: false

docker-build-and-push:
  stage: release
  image: docker:latest
  tags:
    - amd64
  services:
    - name: docker:dind
      command: ["--experimental"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  needs:
    - job: create-release
      artifacts: true
  before_script:
    - |
      apk add --no-cache bash curl jq
      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      docker run --privileged --rm tonistiigi/binfmt --install all
      docker buildx create --use --name multiarch
      docker buildx inspect --bootstrap
  script:
    - |
      set -euo pipefail
      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }
      VERSION="${TAG#${CI_PROJECT_NAME}-}"
      echo "TAG=$TAG VERSION=$VERSION"
      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
      echo "IMAGE=$IMAGE"
      docker buildx build --platform linux/amd64,linux/arm64 -t "$IMAGE:latest" -t "$IMAGE:$VERSION" --push .
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: on_success
      allow_failure: false

docker-build-and-push-native-arm64:
  stage: release
  tags:
    - arm64
  needs:
    - job: create-release
      artifacts: true
    - job: test-job-arm64
      artifacts: true
  script:
    - |
      echo "TAG=$TAG VERSION=$VERSION"
      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
      MAVEN_OPTS=""
      echo "Installing graalvm if not yet present"
      sdk install java ${GRAALVM_VERSION}
      sdk use java ${GRAALVM_VERSION}
      echo "Installing maven if not yet present"
      sdk install maven ${MAVEN_VERSION}
      sdk use maven ${MAVEN_VERSION}
      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }
      VERSION="${TAG#${CI_PROJECT_NAME}-}"
      echo "Version is: ${VERSION}"
      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-arm64"
      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-arm64"
      echo "Versioned image name is: ${IMAGE_VERSIONED}"
      echo "Latest image name is: ${IMAGE_LATEST}"
      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      echo "Running native arm64 build..."
      ./mvnw $MAVEN_CLI_OPTS -Pnative -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}"
#      echo "Tag latest"
      #docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
      #echo "Push both tags"
      #docker push "${IMAGE_VERSIONED}"
      #docker push "${IMAGE_LATEST}"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: on_success
      allow_failure: false

docker-build-and-push-native-amd64-v1:
  stage: release
  image: ridiekel/base-test:latest
  tags:
    - amd64
  needs:
    - job: create-release
      artifacts: true
  script:
    - |
      BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-march=x86-64"
      VERSION_SUFFIX="-v1"      

      echo "TAG=$TAG VERSION=$VERSION"

      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }

      VERSION="${TAG#${CI_PROJECT_NAME}-}"      
      echo "Version is: ${VERSION}"
      
      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-amd64${VERSION_SUFFIX}"
      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-amd64${VERSION_SUFFIX}"
      echo "Versioned image name is: ${IMAGE_VERSIONED}"
      echo "Latest image name is: ${IMAGE_LATEST}"
      
      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      
      echo "Running native amd64 build..."
      echo "Architecture: ${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
      ./mvnw $MAVEN_CLI_OPTS -Pnative -Dnative-image.args="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}" -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}"
      
#      echo "Tag latest"
      #docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
      #echo "Push both tags"
      #docker push "${IMAGE_VERSIONED}"
      #docker push "${IMAGE_LATEST}"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: on_success
      allow_failure: false

docker-build-and-push-native-amd64-v2:
  stage: release
  image: ridiekel/base-test:latest
  tags:
    - amd64
  needs:
    - job: create-release
      artifacts: true
  script:
    - |
      VERSION_SUFFIX="-v2"      
      BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-march=x86-64-v2"
      BP_LOG_LEVEL=DEBUG

      echo "TAG=$TAG VERSION=$VERSION"

      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }

      VERSION="${TAG#${CI_PROJECT_NAME}-}"      
      echo "Version is: ${VERSION}"
      
      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-amd64${VERSION_SUFFIX}"
      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-amd64${VERSION_SUFFIX}"
      echo "Versioned image name is: ${IMAGE_VERSIONED}"
      echo "Latest image name is: ${IMAGE_LATEST}"
      
      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      
      echo "Running native amd64 build..."
      echo "Architecture: ${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
      ./mvnw $MAVEN_CLI_OPTS -Pnative -Dnative-image.args="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}" -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}"
      
#      echo "Tag latest"
      #docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
      #echo "Push both tags"
      #docker push "${IMAGE_VERSIONED}"
      #docker push "${IMAGE_LATEST}"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: on_success
      allow_failure: false

docker-build-and-push-native-amd64-v3:
  stage: release
  image: ridiekel/base-test:latest
  tags:
    - amd64
  needs:
    - job: create-release
      artifacts: true
  script:
    - |
      BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-march=x86-64-v3"
      VERSION_SUFFIX="-v3"      

      echo "TAG=$TAG VERSION=$VERSION"

      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }

      VERSION="${TAG#${CI_PROJECT_NAME}-}"      
      echo "Version is: ${VERSION}"
      
      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-amd64${VERSION_SUFFIX}"
      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-amd64${VERSION_SUFFIX}"
      echo "Versioned image name is: ${IMAGE_VERSIONED}"
      echo "Latest image name is: ${IMAGE_LATEST}"
      
      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      
      echo "Running native amd64 build..."
      echo "Architecture: ${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
      ./mvnw $MAVEN_CLI_OPTS -Pnative -Dnative-image.args="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}" -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}"
      
#      echo "Tag latest"
      #docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
      #echo "Push both tags"
      #docker push "${IMAGE_VERSIONED}"
      #docker push "${IMAGE_LATEST}"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: on_success
      allow_failure: false

docker-build-and-push-native-amd64-v4:
  stage: release
  image: ridiekel/base-test:latest
  tags:
    - amd64
  needs:
    - job: create-release
      artifacts: true
  script:
    - |
      BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-march=x86-64-v4"
      VERSION_SUFFIX="-v4"      

      echo "TAG=$TAG VERSION=$VERSION"

      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }

      VERSION="${TAG#${CI_PROJECT_NAME}-}"      
      echo "Version is: ${VERSION}"
      
      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-amd64${VERSION_SUFFIX}"
      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-amd64${VERSION_SUFFIX}"
      IMAGE_LATEST_AMD="${DOCKERHUB_IMAGE}:latest-native-amd64"
      
      echo "Versioned image name is: ${IMAGE_VERSIONED}"
      echo "Latest image name is: ${IMAGE_LATEST}"
      echo "Latest amd64 image name is: ${IMAGE_LATEST_AMD}"
      
      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      
      echo "Running native amd64 build..."
      echo "Architecture: ${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
      ./mvnw $MAVEN_CLI_OPTS -Pnative -Dnative-image.args="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}" -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}"
      
#      echo "Tag latest"
      #docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
      #docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST_AMD}"
      #echo "Push both tags"
      #docker push "${IMAGE_VERSIONED}"
      #docker push "${IMAGE_LATEST}"
      #docker push "${IMAGE_LATEST_AMD}"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
      when: on_success
      allow_failure: false

