#!/usr/bin/env bash

VERSION=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)

VERSION=$(echo "${VERSION}" | awk -F. -v OFS=. '{$NF++}1')

echo""
echo""
echo "***********************************"
echo Setting version to: $VERSION
echo "***********************************"
echo""
echo""
./mvnw versions:set -DnewVersion=${VERSION}

VERSION=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)

echo""
echo""
echo "***********************************"
echo Building version: $VERSION
echo "***********************************"
echo""
echo""

./mvnw clean package verify -DskipTests=true

echo "---------------------------------------------------------------------"
cat Dockerfile
echo "---------------------------------------------------------------------"

docker buildx build \
  --platform "linux/amd64,linux/arm64" \
  -t ridiekel/jeletask2mqtt:latest \
  -t "ridiekel/jeletask2mqtt:${VERSION}" \
  --push \
  .
