teletask:
  configFile: "file:/teletask2mqtt/config.json"
  central:
    host: "localhost"
    port: 1234
    id: "MAN_${teletask.central.host}_${teletask.central.port}"
    version: "@project.version@"
  mqtt:
    host: "localhost"
    port: 1883
    username: ""
    password: ""
    retained: "true"
    clientId: "teletask2mqtt"
    prefix: "teletask2mqtt"
    discovery_prefix: "homeassistant"
  trace:
    retention: P30D      # hoe lang bewaren (bv. 7 dagen)
    cleanup:
      enabled: true     # cleanup aan/uit
      interval: PT1M   # hoe vaak opruimen (bv. elke 15 min)
  db:
    dir: /data

spring:
  main:
    banner-mode: off
  application:
    name: teletask2mqtt
  boot:
    admin:
      client:
        url: http://localhost:8080/sba
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
      context-path: "/sba"
  security:
    user:
      name: client
      password: client

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'caches'
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
    env:
      show-values: when_authorized
    configprops:
      show-values: when_authorized
    quartz:
      show-values: when_authorized
  datasource:
    url: jdbc:h2:file:${teletask.db.dir}/mqtt-trace;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # voor dev: update; voor prod: liever validate + migrations (Flyway/Liquibase)
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  level:
    org.hibernate.SQL: WARN
    io.github.ridiekel.jeletask: INFO
#    io.github.ridiekel.jeletask: DEBUG
#    io.github.ridiekel.jeletask: TRACE
